name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Cache mypy
        uses: actions/cache@v2
        with:
          path: .mypy_cache
          key: mypy-cache
      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
      - name: Lint with pylint
        run: |
          pylint -j`nproc` app